openapi: "3.0.0"
info: 
  title: Tshirt site API
  description: an API for ecomm store
  version: 1.1.0
  contact: 
    email: rahulkashyap4019@gmail.com
    url: "https://github.com/rahul4019"


servers: 
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host
    variables: 
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol: 
        enum: 
          - http
          - https
        default: http

components: 
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy: 
    get: 
      tags: 
        - Home
      summary:  returns a greet message
      responses: 
        200:
          description: All good success
          content: 
            application/json: 
              schema:   
                type: string
                example: "mystring" 
        400: 
          description: Bad request
        500: 
          description: Internal server error

